version: "3.7"
services:
  apache:
    image: juanluisbaptiste/apache:dev
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./volumes/wordpress/:/var/www/html/
    container_name: apache
networks:
  frontend:
  backend:
